server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
  redis:
    #database: 0
    #host: localhost
    #port: 6379
    cluster:
      nodes: 192.168.177.142:6379,192.168.177.143:6379,192.168.177.144:6379
    password:
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sd.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
#tk.mybatis
mapper:
  b-e-f-o-r-e: true

borrow:
  student:
    bookNum: 10
    borrowDays: 30
  teacher:
    bookNum: 20
    borrowDays: 60
  customer:
    bookNum: 3
    borrowDays: 30