server:
  port: 1003
spring:
  application:
    name: teaching
  datasource:
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sd.teaching.model

#tk.mybatis
mapper:
  b-e-f-o-r-e: true